[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_todo = "DMeNA3KKDFkK6wNLYVGts4zHmfLkY64c1wTfcqapubYB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha"
